# Generated by Django 6.1 on 2026-09-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_manage', '0002_equipe_piloto_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
